
[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.run]
command = "cargo"
args = ["run"]

[tasks.css]
command = "tailwindcss"
args = ["-i", "src/input.css", "-o", "src/tailwind.css"]

[tasks.dev]
dependencies = [
	"format",
	"css",
	"run",
	]
