
[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.lint]
command = "cargo"
args = ["clippy"]

[tasks.dev]
dependencies = [
	"format",
	"lint",
	"build",
	]
