
[tasks.desktop]
workspace = false
env = { "CARGO_MAKE_WORKSPACE_SKIP_MEMBERS" = ["web"] }
run_task = { name = "dev", fork = true }

[tasks.web]
workspace = false
env = { "CARGO_MAKE_WORKSPACE_SKIP_MEMBERS" = ["desktop"] }
run_task = { name = "dev", fork = true }

