
[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.css]
command = "sass"
args = ["--no-source-map", "src/input.scss", "src/custom.css"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = [
	"format",
	"css",
	]

[tasks.dev]
dependencies = [
	"format",
	"css",
	]

